### ISSUE TITLE
请教一下如何获得内容中图片的复现结果

### ISSUE THREAD

**Issue by Weifan1226** [AzureStarz/paying_attention_to_the_source#1]
您好：

请教您一下获得图片中热力图的代码在库里么，还是说应该用别的办法实现。我也想实现一下热力图的结果。
![截屏2024-10-07 11 36 50](https://github.com/user-attachments/assets/7ad07755-b423-4172-b4df-cff7d00f2348)

谢谢！

**Comment by AzureStarz** [comment]
You can refer to the code available here: https://github.com/mt-upc/transformer-contributions

**Comment by Weifan1226** [comment]
谢谢！
我参考一下

**Comment by Weifan1226** [comment]
作者您好，

我还是存在一些疑问，比如这个库和transforer-contributions里的使用的tokenizer是不一样的，当前库是Llama的tokenizer划分的粒度更细，Bert的tokenzier更近似于词元分割。 但是我看我们文章的图虽然是llama模型，但是里面都是完整的单词为单位的。请问这个地方我们是额外进行处理了么。

**Comment by AzureStarz** [comment]
As you said, we first calculate the contributions on all subwords generated by the llama tokenizer. Then, we aggregate the subwords' contribution to a complete word so that we can draw the heatmap that conforms to human reading habits.
